/*
  Register definitions for slave core: GPIO Port

  * File           : sw/oup_wishbone.h
  * Author         : auto-generated by wbgen2 from oup_wbgen2.wb
  * Created        : Mon Jan  1 12:03:32 2024
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE oup_wbgen2.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_OUP_WBGEN2_WB
#define __WBGEN2_REGDEFS_OUP_WBGEN2_WB

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <inttypes.h>
#endif

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Pin direction register */

/* definitions for register: Pin input state register */

/* definitions for register: Port output register */

/* definitions for register: Set output pin register */

/* definitions for register: Clear output pin register */

PACKED struct GPIO_WB {
  /* [0x0]: REG Pin direction register */
  uint32_t DDR;
  /* [0x4]: REG Pin input state register */
  uint32_t PSR;
  /* [0x8]: REG Port output register */
  uint32_t PDR;
  /* padding to: 4 words */
  uint32_t __padding_0[1];
  /* [0x10]: REG Set output pin register */
  uint32_t SOPR;
  /* [0x14]: REG Clear output pin register */
  uint32_t COPR;
};

#endif
