name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get -y install lua5.1
    
    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Build and run check
      run: make check

